name: 'MathDown (legacy)'
description: 'Markdown to HTML on steroids'
inputs:
  toc:
    description: 'enable table of contents'
    default: 'true'
  pagetitle:
    description: 'set page title'
    default: ''
  input:
    description: 'input file path'
    required: true
  output:
    description: 'output file path'
    required: true
  ref:
    description: 'assets git ref'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-t'
    - ${{ inputs.toc }}
    - '-p'
    - ${{ inputs.pagetitle }}
    - '-i'
    - ${{ inputs.input }}
    - '-o'
    - ${{ inputs.output }}
    - '-r'
    - ${{ inputs.ref }}
